require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
install! 'cocoapods', :deterministic_uuids => false

source 'https://cdn.cocoapods.org/'

target 'Basic-tvOS' do
  platform :tvos, '15.0'

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  use_native_modules!

  target 'Basic-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'Basic-tvOS-PROD' do
  platform :tvos, '15.0'

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  use_native_modules!
end

post_install do |installer|

  react_native_post_install(installer)
end
