require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

install! 'cocoapods', deterministic_uuids: false
use_frameworks! linkage: :static

platform :ios, '14.0'

source 'https://cdn.cocoapods.org/'

target 'Basic' do
  config = use_native_modules!

  use_react_native!(
    path: config[:reactNativePath],
    hermes_enabled: false,
    fabric_enabled: true
  )

  use_native_modules!

  target 'BasicTests' do
    inherit! :search_paths
  end
end

target 'BasicProduction' do
  config = use_native_modules!

  use_react_native!(
    path: config[:reactNativePath],
    hermes_enabled: false,
    fabric_enabled: true
  )

  use_native_modules!
end

# Reanimated fix for use_frameworks!
pre_install do |installer|
  installer.pod_targets.each do |pod|
    if pod.name.eql?('react-native-reanimated')
      puts 'Applying Reanimated workaround'
      def pod.build_type;
        Pod::BuildType.static_library
      end
    end
  end
end

post_install do |installer|
  react_native_post_install(installer)

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
