$RCT_NEW_ARCH_ENABLED = ENV['RCT_NEW_ARCH_ENABLED'] == '1' || ENV['RCT_NEW_ARCH_ENABLED'].nil?

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

MIN_IOS_OVERRIDE = '16.0'
if Gem::Version.new(MIN_IOS_OVERRIDE) > Gem::Version.new(min_ios_version_supported)
    min_ios_version_supported = MIN_IOS_OVERRIDE
end

platform :ios, min_ios_version_supported

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Basic' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    fabric_enabled: $RCT_NEW_ARCH_ENABLED,
    new_arch_enabled: $RCT_NEW_ARCH_ENABLED
  )

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  setup_permissions([
    'LocationAccuracy',
    'LocationAlways',
    'LocationWhenInUse',
    'Notifications',
  ])

  target 'BasicTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'BasicProduction' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    fabric_enabled: $RCT_NEW_ARCH_ENABLED,
    new_arch_enabled: $RCT_NEW_ARCH_ENABLED
  )

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  setup_permissions([
    'LocationAccuracy',
    'LocationAlways',
    'LocationWhenInUse',
    'Notifications',
  ])
end

post_install do |installer|
  config = use_native_modules!

  # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
  react_native_post_install(
    installer,
    config[:reactNativePath],
    :mac_catalyst_enabled => false,
    # :ccache_enabled => true
  )
end
