require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.2'

source 'https://cdn.cocoapods.org/'

target 'BasicLinkedPaywall' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!({ "Flipper-DoubleConversion" => "1.1.7" })
  
  use_native_modules!

  target 'BasicLinkedPaywallTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BasicLinkedPaywall-tvOS' do
    # Pods for BasicLinkedPaywall-tvOS

    target 'BasicLinkedPaywall-tvOSTests' do
      inherit! :search_paths
      # Pods for testing
    end

  end

  
  post_install do |installer|
    react_native_post_install(installer)
    #__apply_Xcode_12_5_M1_post_install_workaround(installer)

      puts("Attempting to add Nami.xcframework reference to react-native-nami-sdk project.")
  installer.pods_project.targets.each do |target|
    if target.name  == "react-native-nami-sdk"
      puts("Found react-native-nami-sdk target.")
      all_filerefs = installer.pods_project.files
      all_filerefs.each do |fileref|
         if fileref.path.end_with? "Nami.xcframework"
          puts("Found Nami.xcframework fileref.")
          build_phase = target.frameworks_build_phase
          puts("Determining if react-native-nami-sdk build phase needs correction.")
          unless build_phase.files_references.include?(fileref)
            puts("Adding Nami.xcframework to react-native-nami-sdk target")            
            build_phase.add_file_reference(fileref)
          end
         end
      end
    end
  end
  end
end


