name: Build Bridge

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Git Tag, Branch or SHA to build"
        required: true
        default: "develop"
      earlyaccess:
        description: "Is this a early access build?"
        default: true
        type: boolean

jobs:
  build:
    name: Build Bridge release
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      id-token: write
    steps:

      # clone the repo at a specific version
      - name: Checkout ${{ inputs.ref }}
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}

      # Setup .npmrc file to publish to npm
      - name: Setup Node
        uses: actions/setup-node@v3        
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      # human error checks
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Release Preflight Checks
        run: |
          python3 build-utils/preflight.py
        env:
          NAMI_SDK_VERSION: ${{ inputs.version }}

      - name: Run Yarn
        run: |
          yarn --frozen-lockfile

      - name: Publish
        run: |
        echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_ACCESS_TOKEN  }}' > ${{ github.workspace }}/.npmrc
          npm publish --access public

      - name: Create Github Release
        run: |-
          #sh gh-release-command.sh
          echo "Release me"
        env:
          GITHUB_TOKEN: ${{ github.token }}
